#include "native-vulkan-renderer.h"
#include <vulkan/vulkan.h>
#include <vulkan/vulkan_android.h>
#include <android/asset_manager.h>
#include <android/log.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstring>
#include <mutex>
#include <sstream>
#include <vector>

#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "CameraVulkan", __VA_ARGS__)
#define LOGI_NATIVE(...) __android_log_print(ANDROID_LOG_INFO, "NativeCamera", __VA_ARGS__)

namespace {
struct Buffer { VkBuffer buffer{}; VkDeviceMemory memory{}; VkDeviceSize size{}; };
struct Texture { VkImage image{}; VkDeviceMemory memory{}; VkImageView view{}; int w{}, h{}; };
struct Yuv420To444Push { uint32_t width, height, srcYStrideWords, srcUvStrideWords, srcYPlaneWords, srcUvPlaneWords, dstStrideWords, dstPlaneWords; };
struct DownsamplePush { uint32_t src_w_u32, dst_w_u32, dst_base_word, tile_count_x, tile_count_y; };
struct ResizePush { uint32_t src_w_u32, dst_w_u32, dst_base_word, src_w, src_h, dst_w, dst_h, dst_word_count_x; };
struct SobelPush { uint32_t width, height, strideWords, planeWords; };
struct MedianPush { uint32_t width, height, strideWords, planeWords, edgeThresholdY, edgeThresholdChroma; };
struct PlaneStorage { int w{}, h{}, paddedW{}, paddedH{}; uint32_t strideWords{}, planeWords{}; };
struct DownsamplePlan { uint32_t passCount{}; int modes[2]{}; int midW{}, midH{}, outW{}, outH{}; };
struct Renderer {
    VkInstance instance{}; VkSurfaceKHR surface{}; VkPhysicalDevice physical{};
    VkDevice device{}; uint32_t queueFamily{}; VkQueue queue{};
    VkSwapchainKHR swapchain{}; VkFormat swapFormat{}; VkExtent2D extent{};
    VkSurfaceTransformFlagBitsKHR surfaceTransform{VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR};
    std::vector<VkImage> swapImages; std::vector<VkImageView> swapViews;
    VkRenderPass renderPass{}; VkDescriptorSetLayout setLayout{}; VkPipelineLayout pipelineLayout{};
    VkPipeline pipeline{}; std::vector<VkFramebuffer> framebuffers;
    VkCommandPool commandPool{}; VkCommandBuffer command{};
    VkQueryPool integratedQueryPool{}; VkPhysicalDeviceProperties properties{}; bool integratedQueryValid{};
    VkSemaphore acquired{}, finished{}; VkFence fence{};
    VkDescriptorPool descriptorPool{}; VkDescriptorSet descriptor{}; VkSampler sampler{};
    std::array<Texture,3> textures{}; VkBuffer staging{}; VkDeviceMemory stagingMemory{}; size_t stagingSize{};
    VkDescriptorPool computeDescriptorPool{}; VkDescriptorSetLayout twoBufferSetLayout{}, downsampleSetLayout{}, sobelSetLayout{}, medianSetLayout{};
    VkPipelineLayout yuv420To444Layout{}, downsampleLayout{}, resizeLayout{}, sobelLayout{}, medianLayout{}; VkPipeline yuv420To444Pipeline{}, downsample3To2Pipeline{}, downsample4To2Pipeline{}, downsample4To3Pipeline{}, resizePipeline{}, sobelPipeline{}, medianPipeline{};
    VkDescriptorSet yuv420To444Set{}; std::array<VkDescriptorSet,6> downsampleSets{}; std::array<VkDescriptorSet,3> resizeSets{}, sobelPlaneSets{}, medianPlaneSets{}; VkDescriptorSet sobelSet{}, medianSet{}; Buffer compactUpload{}, yuv444Expanded{}, yuvIntermediate{}, sobelMask{}; std::array<Buffer,3> yuvDownsampled{}, yuvFiltered{}; uint32_t frameBufferIndex{};
    int computeW{}, computeH{}, computeDesiredW{}, computeDesiredH{}, computeInputFormat{}, computeOutW{}, computeOutH{}, computePaddedOutW{}, computePaddedOutH{}, computeChromaOutW{}, computeChromaOutH{};
    DownsamplePlan computePlan{}; PlaneStorage inputY{}, inputUv{}, midY{}, midUv{}, outY{}, outUv{};
    uint32_t computeSrcStrideWords{}, computeSrcPlaneWords{}, computeSrcUvStrideWords{}, computeSrcUvPlaneWords{}, computeStrideWords{}, computePlaneWords{}, computeChromaStrideWords{}, computeChromaPlaneWords{};
    AAssetManager* assets{}; bool ready{}; bool latestFilteredReady{}; uint32_t filteredFrameCount{};
} r;
std::mutex mutex;

bool ok(VkResult value, const char* what) {
    if (value == VK_SUCCESS) return true;
    LOGE("%s failed: %d", what, value); return false;
}
uint32_t memoryType(uint32_t bits, VkMemoryPropertyFlags flags) {
    VkPhysicalDeviceMemoryProperties p{}; vkGetPhysicalDeviceMemoryProperties(r.physical, &p);
    for (uint32_t i=0;i<p.memoryTypeCount;i++) if ((bits&(1u<<i)) && (p.memoryTypes[i].propertyFlags&flags)==flags) return i;
    return UINT32_MAX;
}
std::vector<uint8_t> asset(const char* name) {
    AAsset* a=AAssetManager_open(r.assets,name,AASSET_MODE_BUFFER); if(!a) return {};
    size_t n=AAsset_getLength(a); std::vector<uint8_t> out(n); AAsset_read(a,out.data(),n); AAsset_close(a); return out;
}
VkShaderModule shader(const char* name) {
    auto bytes=asset(name); if(bytes.empty()) return VK_NULL_HANDLE;
    VkShaderModuleCreateInfo ci{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO}; ci.codeSize=bytes.size(); ci.pCode=reinterpret_cast<const uint32_t*>(bytes.data());
    VkShaderModule module{}; return ok(vkCreateShaderModule(r.device,&ci,nullptr,&module),name)?module:VK_NULL_HANDLE;
}
bool createBuffer(Buffer& b,VkDeviceSize size,VkBufferUsageFlags usage,VkMemoryPropertyFlags flags,const char* name){
    b.size=size;VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=size;bi.usage=usage;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(!ok(vkCreateBuffer(r.device,&bi,nullptr,&b.buffer),name))return false;
    VkMemoryRequirements req{};vkGetBufferMemoryRequirements(r.device,b.buffer,&req);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=memoryType(req.memoryTypeBits,flags);if(ai.memoryTypeIndex==UINT32_MAX||!ok(vkAllocateMemory(r.device,&ai,nullptr,&b.memory),name))return false;vkBindBufferMemory(r.device,b.buffer,b.memory,0);return true;
}
void destroyBuffer(Buffer& b){if(b.buffer)vkDestroyBuffer(r.device,b.buffer,nullptr);if(b.memory)vkFreeMemory(r.device,b.memory,nullptr);b={};}
void destroyComputeBuffers(){destroyBuffer(r.compactUpload);destroyBuffer(r.yuv444Expanded);destroyBuffer(r.yuvIntermediate);for(auto& b:r.yuvDownsampled)destroyBuffer(b);destroyBuffer(r.sobelMask);for(auto& b:r.yuvFiltered)destroyBuffer(b);r.frameBufferIndex=0;r.latestFilteredReady=false;r.filteredFrameCount=0;r.computeW=0;r.computeH=0;r.computeDesiredW=0;r.computeDesiredH=0;r.computeInputFormat=0;r.computeOutW=0;r.computeOutH=0;r.computePaddedOutW=0;r.computePaddedOutH=0;r.computeChromaOutW=0;r.computeChromaOutH=0;r.computePlan={};r.inputY={};r.inputUv={};r.midY={};r.midUv={};r.outY={};r.outUv={};r.computeSrcStrideWords=0;r.computeSrcPlaneWords=0;r.computeSrcUvStrideWords=0;r.computeSrcUvPlaneWords=0;r.computeStrideWords=0;r.computePlaneWords=0;r.computeChromaStrideWords=0;r.computeChromaPlaneWords=0;}
VkPipeline createComputePipeline(const char* assetName,VkPipelineLayout layout){
    VkShaderModule mod=shader(assetName);if(!mod)return VK_NULL_HANDLE;VkPipelineShaderStageCreateInfo stage{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO};stage.stage=VK_SHADER_STAGE_COMPUTE_BIT;stage.module=mod;stage.pName="main";VkComputePipelineCreateInfo ci{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};ci.stage=stage;ci.layout=layout;VkPipeline p{};ok(vkCreateComputePipelines(r.device,VK_NULL_HANDLE,1,&ci,nullptr,&p),assetName);vkDestroyShaderModule(r.device,mod,nullptr);return p;
}
void destroyComputeResources(){
    if(!r.device)return;
    destroyComputeBuffers();
    if(r.computeDescriptorPool)vkDestroyDescriptorPool(r.device,r.computeDescriptorPool,nullptr);
    if(r.yuv420To444Pipeline)vkDestroyPipeline(r.device,r.yuv420To444Pipeline,nullptr);if(r.downsample3To2Pipeline)vkDestroyPipeline(r.device,r.downsample3To2Pipeline,nullptr);if(r.downsample4To2Pipeline)vkDestroyPipeline(r.device,r.downsample4To2Pipeline,nullptr);if(r.downsample4To3Pipeline)vkDestroyPipeline(r.device,r.downsample4To3Pipeline,nullptr);if(r.resizePipeline)vkDestroyPipeline(r.device,r.resizePipeline,nullptr);if(r.sobelPipeline)vkDestroyPipeline(r.device,r.sobelPipeline,nullptr);if(r.medianPipeline)vkDestroyPipeline(r.device,r.medianPipeline,nullptr);
    if(r.yuv420To444Layout)vkDestroyPipelineLayout(r.device,r.yuv420To444Layout,nullptr);if(r.downsampleLayout)vkDestroyPipelineLayout(r.device,r.downsampleLayout,nullptr);if(r.resizeLayout)vkDestroyPipelineLayout(r.device,r.resizeLayout,nullptr);if(r.sobelLayout)vkDestroyPipelineLayout(r.device,r.sobelLayout,nullptr);if(r.medianLayout)vkDestroyPipelineLayout(r.device,r.medianLayout,nullptr);
    if(r.twoBufferSetLayout)vkDestroyDescriptorSetLayout(r.device,r.twoBufferSetLayout,nullptr);if(r.downsampleSetLayout&&r.downsampleSetLayout!=r.twoBufferSetLayout)vkDestroyDescriptorSetLayout(r.device,r.downsampleSetLayout,nullptr);if(r.sobelSetLayout)vkDestroyDescriptorSetLayout(r.device,r.sobelSetLayout,nullptr);if(r.medianSetLayout)vkDestroyDescriptorSetLayout(r.device,r.medianSetLayout,nullptr);
    r.computeDescriptorPool={};r.yuv420To444Pipeline={};r.downsample3To2Pipeline={};r.downsample4To2Pipeline={};r.downsample4To3Pipeline={};r.resizePipeline={};r.sobelPipeline={};r.medianPipeline={};r.yuv420To444Layout={};r.downsampleLayout={};r.resizeLayout={};r.sobelLayout={};r.medianLayout={};r.twoBufferSetLayout={};r.downsampleSetLayout={};r.sobelSetLayout={};r.medianSetLayout={};r.yuv420To444Set={};r.downsampleSets={};r.resizeSets={};r.sobelPlaneSets={};r.medianPlaneSets={};r.sobelSet={};r.medianSet={};r.computeW=0;r.computeH=0;r.computeDesiredW=0;r.computeDesiredH=0;r.computeInputFormat=0;r.computeOutW=0;r.computeOutH=0;r.computePaddedOutW=0;r.computePaddedOutH=0;r.computeChromaOutW=0;r.computeChromaOutH=0;r.computePlan={};r.computeSrcStrideWords=0;r.computeSrcPlaneWords=0;r.computeSrcUvStrideWords=0;r.computeSrcUvPlaneWords=0;r.computeStrideWords=0;r.computePlaneWords=0;r.computeChromaStrideWords=0;r.computeChromaPlaneWords=0;
}
void destroyTextures() {
    if(!r.device)return; vkDeviceWaitIdle(r.device);
    if(r.staging)vkDestroyBuffer(r.device,r.staging,nullptr); if(r.stagingMemory)vkFreeMemory(r.device,r.stagingMemory,nullptr);
    r.staging={};r.stagingMemory={};r.stagingSize=0;
    for(auto& t:r.textures){if(t.view)vkDestroyImageView(r.device,t.view,nullptr);if(t.image)vkDestroyImage(r.device,t.image,nullptr);if(t.memory)vkFreeMemory(r.device,t.memory,nullptr);t={};}
}
void destroyAll() {
    if(r.device)vkDeviceWaitIdle(r.device); destroyTextures(); destroyComputeResources();
    if(r.device){
        if(r.integratedQueryPool)vkDestroyQueryPool(r.device,r.integratedQueryPool,nullptr);
        if(r.sampler)vkDestroySampler(r.device,r.sampler,nullptr); if(r.descriptorPool)vkDestroyDescriptorPool(r.device,r.descriptorPool,nullptr);
        if(r.fence)vkDestroyFence(r.device,r.fence,nullptr); if(r.acquired)vkDestroySemaphore(r.device,r.acquired,nullptr); if(r.finished)vkDestroySemaphore(r.device,r.finished,nullptr);
        if(r.commandPool)vkDestroyCommandPool(r.device,r.commandPool,nullptr);
        for(auto f:r.framebuffers)vkDestroyFramebuffer(r.device,f,nullptr); if(r.pipeline)vkDestroyPipeline(r.device,r.pipeline,nullptr);
        if(r.pipelineLayout)vkDestroyPipelineLayout(r.device,r.pipelineLayout,nullptr);if(r.setLayout)vkDestroyDescriptorSetLayout(r.device,r.setLayout,nullptr);
        if(r.renderPass)vkDestroyRenderPass(r.device,r.renderPass,nullptr);for(auto v:r.swapViews)vkDestroyImageView(r.device,v,nullptr);
        if(r.swapchain)vkDestroySwapchainKHR(r.device,r.swapchain,nullptr);vkDestroyDevice(r.device,nullptr);
    }
    if(r.surface&&r.instance)vkDestroySurfaceKHR(r.instance,r.surface,nullptr);if(r.instance)vkDestroyInstance(r.instance,nullptr);r={};
}
bool createTexture(Texture& t,int w,int h) {
    t.w=w;t.h=h;VkImageCreateInfo ci{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};ci.imageType=VK_IMAGE_TYPE_2D;ci.format=VK_FORMAT_R8_UNORM;ci.extent={uint32_t(w),uint32_t(h),1};ci.mipLevels=1;ci.arrayLayers=1;ci.samples=VK_SAMPLE_COUNT_1_BIT;ci.tiling=VK_IMAGE_TILING_OPTIMAL;ci.usage=VK_IMAGE_USAGE_TRANSFER_DST_BIT|VK_IMAGE_USAGE_SAMPLED_BIT;ci.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;
    if(!ok(vkCreateImage(r.device,&ci,nullptr,&t.image),"vkCreateImage"))return false;VkMemoryRequirements req{};vkGetImageMemoryRequirements(r.device,t.image,&req);
    VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=memoryType(req.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);if(ai.memoryTypeIndex==UINT32_MAX||!ok(vkAllocateMemory(r.device,&ai,nullptr,&t.memory),"texture memory"))return false;vkBindImageMemory(r.device,t.image,t.memory,0);
    VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=t.image;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=VK_FORMAT_R8_UNORM;vi.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};return ok(vkCreateImageView(r.device,&vi,nullptr,&t.view),"texture view");
}
bool createFrameResources(int w,int h,int cw,int ch) {
    destroyTextures(); if(!createTexture(r.textures[0],w,h)||!createTexture(r.textures[1],cw,ch)||!createTexture(r.textures[2],cw,ch))return false;
    r.stagingSize=size_t(w)*h+size_t(cw)*ch*2;VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=r.stagingSize;bi.usage=VK_BUFFER_USAGE_TRANSFER_SRC_BIT;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(!ok(vkCreateBuffer(r.device,&bi,nullptr,&r.staging),"staging buffer"))return false;
    VkMemoryRequirements req{};vkGetBufferMemoryRequirements(r.device,r.staging,&req);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=memoryType(req.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);if(ai.memoryTypeIndex==UINT32_MAX||!ok(vkAllocateMemory(r.device,&ai,nullptr,&r.stagingMemory),"staging memory"))return false;vkBindBufferMemory(r.device,r.staging,r.stagingMemory,0);
    std::array<VkDescriptorImageInfo,3> info{};std::array<VkWriteDescriptorSet,3> writes{};for(int i=0;i<3;i++){info[i]={r.sampler,r.textures[i].view,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};writes[i]={VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};writes[i].dstSet=r.descriptor;writes[i].dstBinding=i;writes[i].descriptorCount=1;writes[i].descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;writes[i].pImageInfo=&info[i];}vkUpdateDescriptorSets(r.device,3,writes.data(),0,nullptr);return true;
}
bool createComputeStaticResources(){
    std::array<VkDescriptorSetLayoutBinding,2> twoBufferBindings{};for(uint32_t i=0;i<2;i++){twoBufferBindings[i].binding=i;twoBufferBindings[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;twoBufferBindings[i].descriptorCount=1;twoBufferBindings[i].stageFlags=VK_SHADER_STAGE_COMPUTE_BIT;}
    VkDescriptorSetLayoutCreateInfo twoInfo{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};twoInfo.bindingCount=2;twoInfo.pBindings=twoBufferBindings.data();if(!ok(vkCreateDescriptorSetLayout(r.device,&twoInfo,nullptr,&r.twoBufferSetLayout),"two-buffer set layout"))return false;
    r.downsampleSetLayout=r.twoBufferSetLayout;
    std::array<VkDescriptorSetLayoutBinding,2> sobelBindings{};for(uint32_t i=0;i<2;i++){sobelBindings[i].binding=i;sobelBindings[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;sobelBindings[i].descriptorCount=1;sobelBindings[i].stageFlags=VK_SHADER_STAGE_COMPUTE_BIT;}
    VkDescriptorSetLayoutCreateInfo sobelInfo{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};sobelInfo.bindingCount=2;sobelInfo.pBindings=sobelBindings.data();if(!ok(vkCreateDescriptorSetLayout(r.device,&sobelInfo,nullptr,&r.sobelSetLayout),"sobel set layout"))return false;
    std::array<VkDescriptorSetLayoutBinding,3> medianBindings{};for(uint32_t i=0;i<3;i++){medianBindings[i].binding=i;medianBindings[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;medianBindings[i].descriptorCount=1;medianBindings[i].stageFlags=VK_SHADER_STAGE_COMPUTE_BIT;}
    VkDescriptorSetLayoutCreateInfo medianInfo{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};medianInfo.bindingCount=3;medianInfo.pBindings=medianBindings.data();if(!ok(vkCreateDescriptorSetLayout(r.device,&medianInfo,nullptr,&r.medianSetLayout),"median set layout"))return false;
    VkPushConstantRange yuv420Push{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(Yuv420To444Push)};VkPipelineLayoutCreateInfo y420pl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};y420pl.setLayoutCount=1;y420pl.pSetLayouts=&r.twoBufferSetLayout;y420pl.pushConstantRangeCount=1;y420pl.pPushConstantRanges=&yuv420Push;if(!ok(vkCreatePipelineLayout(r.device,&y420pl,nullptr,&r.yuv420To444Layout),"yuv420_to_444 layout"))return false;
    VkPushConstantRange downPush{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(DownsamplePush)};VkPipelineLayoutCreateInfo dpl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};dpl.setLayoutCount=1;dpl.pSetLayouts=&r.downsampleSetLayout;dpl.pushConstantRangeCount=1;dpl.pPushConstantRanges=&downPush;if(!ok(vkCreatePipelineLayout(r.device,&dpl,nullptr,&r.downsampleLayout),"downsample layout"))return false;
    VkPushConstantRange resizePush{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(ResizePush)};VkPipelineLayoutCreateInfo rpl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};rpl.setLayoutCount=1;rpl.pSetLayouts=&r.downsampleSetLayout;rpl.pushConstantRangeCount=1;rpl.pPushConstantRanges=&resizePush;if(!ok(vkCreatePipelineLayout(r.device,&rpl,nullptr,&r.resizeLayout),"resize layout"))return false;
    VkPushConstantRange sobelPush{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(SobelPush)};VkPipelineLayoutCreateInfo spl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};spl.setLayoutCount=1;spl.pSetLayouts=&r.sobelSetLayout;spl.pushConstantRangeCount=1;spl.pPushConstantRanges=&sobelPush;if(!ok(vkCreatePipelineLayout(r.device,&spl,nullptr,&r.sobelLayout),"sobel layout"))return false;
    VkPushConstantRange medianPush{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(MedianPush)};VkPipelineLayoutCreateInfo mpl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};mpl.setLayoutCount=1;mpl.pSetLayouts=&r.medianSetLayout;mpl.pushConstantRangeCount=1;mpl.pPushConstantRanges=&medianPush;if(!ok(vkCreatePipelineLayout(r.device,&mpl,nullptr,&r.medianLayout),"median layout"))return false;
    r.yuv420To444Pipeline=createComputePipeline("yuv420_to_yuv444.comp.spv",r.yuv420To444Layout);r.downsample3To2Pipeline=createComputePipeline("downsample_3to2.comp.spv",r.downsampleLayout);r.downsample4To2Pipeline=createComputePipeline("downsample_4to2.comp.spv",r.downsampleLayout);r.downsample4To3Pipeline=createComputePipeline("downsample_4to3.comp.spv",r.downsampleLayout);r.resizePipeline=createComputePipeline("resize_plane.comp.spv",r.resizeLayout);r.sobelPipeline=createComputePipeline("optimized_sobel_compact.comp.spv",r.sobelLayout);r.medianPipeline=createComputePipeline("optimized_median_v2_compact.comp.spv",r.medianLayout);if(!r.yuv420To444Pipeline||!r.downsample3To2Pipeline||!r.downsample4To2Pipeline||!r.downsample4To3Pipeline||!r.resizePipeline||!r.sobelPipeline||!r.medianPipeline)return false;
    VkDescriptorPoolSize poolSize{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,48};VkDescriptorPoolCreateInfo pool{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};pool.maxSets=18;pool.poolSizeCount=1;pool.pPoolSizes=&poolSize;if(!ok(vkCreateDescriptorPool(r.device,&pool,nullptr,&r.computeDescriptorPool),"compute descriptor pool"))return false;
    VkDescriptorSetAllocateInfo y420a{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};y420a.descriptorPool=r.computeDescriptorPool;y420a.descriptorSetCount=1;y420a.pSetLayouts=&r.twoBufferSetLayout;if(!ok(vkAllocateDescriptorSets(r.device,&y420a,&r.yuv420To444Set),"yuv420_to_444 descriptor"))return false;
    VkDescriptorSetLayout downLayouts[6]={r.downsampleSetLayout,r.downsampleSetLayout,r.downsampleSetLayout,r.downsampleSetLayout,r.downsampleSetLayout,r.downsampleSetLayout};VkDescriptorSetAllocateInfo da{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};da.descriptorPool=r.computeDescriptorPool;da.descriptorSetCount=6;da.pSetLayouts=downLayouts;if(!ok(vkAllocateDescriptorSets(r.device,&da,r.downsampleSets.data()),"downsample descriptors"))return false;
    VkDescriptorSetLayout resizeLayouts[3]={r.downsampleSetLayout,r.downsampleSetLayout,r.downsampleSetLayout};VkDescriptorSetAllocateInfo ra{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};ra.descriptorPool=r.computeDescriptorPool;ra.descriptorSetCount=3;ra.pSetLayouts=resizeLayouts;if(!ok(vkAllocateDescriptorSets(r.device,&ra,r.resizeSets.data()),"resize descriptors"))return false;
    VkDescriptorSetLayout sobelPlaneLayouts[3]={r.sobelSetLayout,r.sobelSetLayout,r.sobelSetLayout};VkDescriptorSetAllocateInfo spa{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};spa.descriptorPool=r.computeDescriptorPool;spa.descriptorSetCount=3;spa.pSetLayouts=sobelPlaneLayouts;if(!ok(vkAllocateDescriptorSets(r.device,&spa,r.sobelPlaneSets.data()),"sobel plane descriptors"))return false;
    VkDescriptorSetLayout medianPlaneLayouts[3]={r.medianSetLayout,r.medianSetLayout,r.medianSetLayout};VkDescriptorSetAllocateInfo mpa{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};mpa.descriptorPool=r.computeDescriptorPool;mpa.descriptorSetCount=3;mpa.pSetLayouts=medianPlaneLayouts;if(!ok(vkAllocateDescriptorSets(r.device,&mpa,r.medianPlaneSets.data()),"median plane descriptors"))return false;
    VkDescriptorSetAllocateInfo sa{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};sa.descriptorPool=r.computeDescriptorPool;sa.descriptorSetCount=1;sa.pSetLayouts=&r.sobelSetLayout;if(!ok(vkAllocateDescriptorSets(r.device,&sa,&r.sobelSet),"sobel descriptor"))return false;
    VkDescriptorSetAllocateInfo ma{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};ma.descriptorPool=r.computeDescriptorPool;ma.descriptorSetCount=1;ma.pSetLayouts=&r.medianSetLayout;if(!ok(vkAllocateDescriptorSets(r.device,&ma,&r.medianSet),"median descriptor"))return false;return true;
}
Buffer& currentYuvDownsampled(){return r.yuvDownsampled[r.frameBufferIndex];}
Buffer& currentYuvFiltered(){return r.yuvFiltered[r.frameBufferIndex];}
int align16(int v){return (v+15)&~15;}
PlaneStorage planeStorage(int w,int h,bool padWidth,bool padHeight){
    PlaneStorage p{};p.w=w;p.h=h;p.paddedW=padWidth?align16(w):w;p.paddedH=padHeight?align16(h):h;p.strideWords=uint32_t((p.paddedW+3)/4);p.planeWords=p.strideWords*uint32_t(p.paddedH);return p;
}
bool derivePlan(int w,int h,int desiredW,int desiredH,DownsamplePlan& plan){
    plan={};plan.outW=w;plan.outH=h;
    if(desiredW>=w||desiredH>=h)return true;
    auto set1=[&](int m,int ow,int oh){plan.passCount=1;plan.modes[0]=m;plan.outW=ow;plan.outH=oh;return true;};
    auto set2=[&](int m0,int mw,int mh,int m1,int ow,int oh){plan.passCount=2;plan.modes[0]=m0;plan.modes[1]=m1;plan.midW=mw;plan.midH=mh;plan.outW=ow;plan.outH=oh;return true;};
    if(w==2560&&h==1440){
        if(desiredW==1920&&desiredH==1080)return set1(5,1920,1080);
        if(desiredW==1280&&desiredH==720)return set1(4,1280,720);
        if(desiredW==854&&desiredH==480)return set2(4,1280,720,6,854,480);
        if(desiredW==640&&desiredH==360)return set2(4,1280,720,4,640,360);
    }
    if(w==1920&&h==1080){
        if(desiredW==1920&&desiredH==1080)return true;
        if(desiredW==1280&&desiredH==720)return set1(3,1280,720);
        if(desiredW==854&&desiredH==480)return set2(3,1280,720,6,854,480);
        if(desiredW==640&&desiredH==360)return set2(3,1280,720,4,640,360);
    }
    return false;
}
VkPipeline pipelineForMode(int mode){return mode==5?r.downsample4To3Pipeline:(mode==3?r.downsample3To2Pipeline:(mode==6?r.resizePipeline:r.downsample4To2Pipeline));}
void bindPlaneSet(VkDescriptorSet set,Buffer& src,uint32_t srcBase,uint32_t srcWords,Buffer& dst){
    VkDescriptorBufferInfo infos[2]={{src.buffer,VkDeviceSize(srcBase)*sizeof(uint32_t),VkDeviceSize(srcWords)*sizeof(uint32_t)},{dst.buffer,0,dst.size}};
    VkWriteDescriptorSet writes[2]={{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET}};
    for(uint32_t i=0;i<2;i++){writes[i].dstSet=set;writes[i].dstBinding=i;writes[i].descriptorCount=1;writes[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;writes[i].pBufferInfo=&infos[i];}
    vkUpdateDescriptorSets(r.device,2,writes,0,nullptr);
}
void updateComputeDescriptors(){
    Buffer& yuvDownsampled=currentYuvDownsampled();Buffer& yuvFiltered=currentYuvFiltered();
    const uint32_t inputWords[3]={r.inputY.planeWords,r.inputUv.planeWords,r.inputUv.planeWords};
    const uint32_t inputBase[3]={0,r.inputY.planeWords,r.inputY.planeWords+r.inputUv.planeWords};
    const uint32_t midWords[3]={r.midY.planeWords,r.midUv.planeWords,r.midUv.planeWords};
    const uint32_t midBase[3]={0,r.midY.planeWords,r.midY.planeWords+r.midUv.planeWords};
    const uint32_t dstPlaneWords[3]={r.outY.planeWords,r.outUv.planeWords,r.outUv.planeWords};
    const uint32_t dstBaseWords[3]={0,r.outY.planeWords,r.outY.planeWords+r.outUv.planeWords};
    if(r.computePlan.passCount==0){
        for(uint32_t c=0;c<3;c++)bindPlaneSet(r.downsampleSets[c],r.compactUpload,inputBase[c],inputWords[c],yuvDownsampled);
    }else if(r.computePlan.passCount==1){
        for(uint32_t c=0;c<3;c++)bindPlaneSet(r.downsampleSets[c],r.compactUpload,inputBase[c],inputWords[c],yuvDownsampled);
    }else{
        for(uint32_t c=0;c<3;c++)bindPlaneSet(r.downsampleSets[c],r.compactUpload,inputBase[c],inputWords[c],r.yuvIntermediate);
        for(uint32_t c=0;c<3;c++){
            if(r.computePlan.modes[1]==6)bindPlaneSet(r.resizeSets[c],r.yuvIntermediate,midBase[c],midWords[c],yuvDownsampled);
            else bindPlaneSet(r.downsampleSets[c+3u],r.yuvIntermediate,midBase[c],midWords[c],yuvDownsampled);
        }
    }
    if(r.computeInputFormat==420){for(uint32_t c=0;c<3;c++){VkDescriptorBufferInfo si[2]={{yuvDownsampled.buffer,VkDeviceSize(dstBaseWords[c])*sizeof(uint32_t),VkDeviceSize(dstPlaneWords[c])*sizeof(uint32_t)},{r.sobelMask.buffer,VkDeviceSize(dstBaseWords[c])*sizeof(uint32_t),VkDeviceSize(dstPlaneWords[c])*sizeof(uint32_t)}};VkWriteDescriptorSet sw[2]={{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET}};for(uint32_t i=0;i<2;i++){sw[i].dstSet=r.sobelPlaneSets[c];sw[i].dstBinding=i;sw[i].descriptorCount=1;sw[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;sw[i].pBufferInfo=&si[i];}vkUpdateDescriptorSets(r.device,2,sw,0,nullptr);VkDescriptorBufferInfo mi[3]={{yuvDownsampled.buffer,VkDeviceSize(dstBaseWords[c])*sizeof(uint32_t),VkDeviceSize(dstPlaneWords[c])*sizeof(uint32_t)},{r.sobelMask.buffer,VkDeviceSize(dstBaseWords[c])*sizeof(uint32_t),VkDeviceSize(dstPlaneWords[c])*sizeof(uint32_t)},{yuvFiltered.buffer,VkDeviceSize(dstBaseWords[c])*sizeof(uint32_t),VkDeviceSize(dstPlaneWords[c])*sizeof(uint32_t)}};VkWriteDescriptorSet mw[3]={{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET}};for(uint32_t i=0;i<3;i++){mw[i].dstSet=r.medianPlaneSets[c];mw[i].dstBinding=i;mw[i].descriptorCount=1;mw[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;mw[i].pBufferInfo=&mi[i];}vkUpdateDescriptorSets(r.device,3,mw,0,nullptr);}}
    VkDescriptorBufferInfo sobelInfos[2]={{yuvDownsampled.buffer,0,yuvDownsampled.size},{r.sobelMask.buffer,0,r.sobelMask.size}};
    VkWriteDescriptorSet sobelWrites[2]={{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET}};
    for(uint32_t i=0;i<2;i++){sobelWrites[i].dstSet=r.sobelSet;sobelWrites[i].dstBinding=i;sobelWrites[i].descriptorCount=1;sobelWrites[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;sobelWrites[i].pBufferInfo=&sobelInfos[i];}
    VkDescriptorBufferInfo medianInfos[3]={{yuvDownsampled.buffer,0,yuvDownsampled.size},{r.sobelMask.buffer,0,r.sobelMask.size},{yuvFiltered.buffer,0,yuvFiltered.size}};
    VkWriteDescriptorSet medianWrites[3]={{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET}};
    for(uint32_t i=0;i<3;i++){medianWrites[i].dstSet=r.medianSet;medianWrites[i].dstBinding=i;medianWrites[i].descriptorCount=1;medianWrites[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;medianWrites[i].pBufferInfo=&medianInfos[i];}
    vkUpdateDescriptorSets(r.device,2,sobelWrites,0,nullptr);vkUpdateDescriptorSets(r.device,3,medianWrites,0,nullptr);
}
bool createComputeFrameResources(int w,int h,int desiredW,int desiredH,int inputFormat){
    if(r.computeW==w&&r.computeH==h&&r.computeDesiredW==desiredW&&r.computeDesiredH==desiredH&&r.computeInputFormat==inputFormat&&r.yuvFiltered[0].buffer)return true;
    vkDeviceWaitIdle(r.device);destroyComputeBuffers();if((w&3)||w<=0||h<=0)return false;if(inputFormat==420&&((w%16)!=0||(h%4)!=0))return false;
    DownsamplePlan plan{};if(!derivePlan(w,h,desiredW,desiredH,plan)){LOGE("No downsample plan for %dx%d -> desired %dx%d",w,h,desiredW,desiredH);return false;}
    const int outW=plan.outW,outH=plan.outH;const int chromaRealW=inputFormat==420?(outW+1)/2:outW,chromaRealH=inputFormat==420?outH/2:outH;
    r.computeW=w;r.computeH=h;r.computeDesiredW=desiredW;r.computeDesiredH=desiredH;r.computeInputFormat=inputFormat;r.computeOutW=outW;r.computeOutH=outH;r.computePlan=plan;
    r.inputY=planeStorage(w,h,false,false);r.inputUv=inputFormat==420?planeStorage(w/2,h/2,false,false):planeStorage(w,h,false,false);
    r.outY=planeStorage(outW,outH,inputFormat==420,false);r.outUv=planeStorage(chromaRealW,chromaRealH,inputFormat==420,inputFormat==420);
    r.computePaddedOutW=r.outY.paddedW;r.computePaddedOutH=r.outY.paddedH;r.computeChromaOutW=r.outUv.paddedW;r.computeChromaOutH=r.outUv.paddedH;
    r.computeSrcStrideWords=r.inputY.strideWords;r.computeSrcPlaneWords=r.inputY.planeWords;r.computeSrcUvStrideWords=r.inputUv.strideWords;r.computeSrcUvPlaneWords=r.inputUv.planeWords;r.computeStrideWords=r.outY.strideWords;r.computePlaneWords=r.outY.planeWords;r.computeChromaStrideWords=r.outUv.strideWords;r.computeChromaPlaneWords=r.outUv.planeWords;
    if(plan.passCount==2){r.midY=planeStorage(plan.midW,plan.midH,true,false);r.midUv=inputFormat==420?planeStorage((plan.midW+1)/2,plan.midH/2,true,true):planeStorage(plan.midW,plan.midH,true,false);}
    VkDeviceSize srcBytes=inputFormat==420?(VkDeviceSize(r.inputY.planeWords)+VkDeviceSize(r.inputUv.planeWords)*2u)*sizeof(uint32_t):VkDeviceSize(r.inputY.planeWords)*3u*sizeof(uint32_t);VkDeviceSize dstWords=inputFormat==420?VkDeviceSize(r.outY.planeWords)+VkDeviceSize(r.outUv.planeWords)*2u:VkDeviceSize(r.outY.planeWords)*3u;VkDeviceSize dstBytes=dstWords*sizeof(uint32_t);
    if(!createBuffer(r.compactUpload,srcBytes,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_TRANSFER_SRC_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,"camera compact upload"))return false;
    VkBufferUsageFlags storageTransfer=VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_TRANSFER_SRC_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT;
    if(plan.passCount==2){VkDeviceSize midWords=VkDeviceSize(r.midY.planeWords)+VkDeviceSize(r.midUv.planeWords)*2u;if(!createBuffer(r.yuvIntermediate,midWords*sizeof(uint32_t),storageTransfer,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,"camera yuv intermediate"))return false;}
    for(uint32_t i=0;i<3;i++)if(!createBuffer(r.yuvDownsampled[i],dstBytes,storageTransfer,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,"camera yuv downsampled"))return false;
    if(!createBuffer(r.sobelMask,dstBytes,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,"camera sobel mask"))return false;
    for(uint32_t i=0;i<3;i++)if(!createBuffer(r.yuvFiltered[i],dstBytes,storageTransfer,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,"camera yuv filtered"))return false;
    r.frameBufferIndex=0;updateComputeDescriptors();return true;
}
bool init(ANativeWindow* window,AAssetManager* assets) {
    r.assets=assets;VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.pApplicationName="CameraPipeline";app.apiVersion=VK_API_VERSION_1_0;const char* iext[]={VK_KHR_SURFACE_EXTENSION_NAME,VK_KHR_ANDROID_SURFACE_EXTENSION_NAME};
    VkInstanceCreateInfo ici{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ici.pApplicationInfo=&app;ici.enabledExtensionCount=2;ici.ppEnabledExtensionNames=iext;if(!ok(vkCreateInstance(&ici,nullptr,&r.instance),"vkCreateInstance"))return false;
    VkAndroidSurfaceCreateInfoKHR sci{VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR};sci.window=window;if(!ok(vkCreateAndroidSurfaceKHR(r.instance,&sci,nullptr,&r.surface),"vkCreateAndroidSurfaceKHR"))return false;
    uint32_t pc=0;vkEnumeratePhysicalDevices(r.instance,&pc,nullptr);std::vector<VkPhysicalDevice> ps(pc);vkEnumeratePhysicalDevices(r.instance,&pc,ps.data());
    for(auto p:ps){uint32_t qc=0;vkGetPhysicalDeviceQueueFamilyProperties(p,&qc,nullptr);std::vector<VkQueueFamilyProperties> qp(qc);vkGetPhysicalDeviceQueueFamilyProperties(p,&qc,qp.data());for(uint32_t i=0;i<qc;i++){VkBool32 present=false;vkGetPhysicalDeviceSurfaceSupportKHR(p,i,r.surface,&present);if((qp[i].queueFlags&VK_QUEUE_GRAPHICS_BIT)&&(qp[i].queueFlags&VK_QUEUE_COMPUTE_BIT)&&present){r.physical=p;r.queueFamily=i;break;}}if(r.physical)break;}if(!r.physical)return false;
    vkGetPhysicalDeviceProperties(r.physical,&r.properties);
    float priority=1;VkDeviceQueueCreateInfo qci{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qci.queueFamilyIndex=r.queueFamily;qci.queueCount=1;qci.pQueuePriorities=&priority;const char* dext=VK_KHR_SWAPCHAIN_EXTENSION_NAME;VkDeviceCreateInfo dci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};dci.queueCreateInfoCount=1;dci.pQueueCreateInfos=&qci;dci.enabledExtensionCount=1;dci.ppEnabledExtensionNames=&dext;if(!ok(vkCreateDevice(r.physical,&dci,nullptr,&r.device),"vkCreateDevice"))return false;vkGetDeviceQueue(r.device,r.queueFamily,0,&r.queue);
    VkSurfaceCapabilitiesKHR caps{};vkGetPhysicalDeviceSurfaceCapabilitiesKHR(r.physical,r.surface,&caps);uint32_t fc=0;vkGetPhysicalDeviceSurfaceFormatsKHR(r.physical,r.surface,&fc,nullptr);std::vector<VkSurfaceFormatKHR> fs(fc);vkGetPhysicalDeviceSurfaceFormatsKHR(r.physical,r.surface,&fc,fs.data());auto sf=fs[0];for(auto f:fs)if(f.format==VK_FORMAT_R8G8B8A8_UNORM||f.format==VK_FORMAT_B8G8R8A8_UNORM){sf=f;break;}r.swapFormat=sf.format;r.extent=caps.currentExtent;r.surfaceTransform=caps.currentTransform;if(r.extent.width==UINT32_MAX)r.extent={uint32_t(ANativeWindow_getWidth(window)),uint32_t(ANativeWindow_getHeight(window))};LOGE("swapchain extent=%ux%u window=%dx%d transform=0x%x",r.extent.width,r.extent.height,ANativeWindow_getWidth(window),ANativeWindow_getHeight(window),r.surfaceTransform);
    uint32_t count=std::max(2u,caps.minImageCount);if(caps.maxImageCount&&count>caps.maxImageCount)count=caps.maxImageCount;VkSwapchainCreateInfoKHR sw{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};sw.surface=r.surface;sw.minImageCount=count;sw.imageFormat=sf.format;sw.imageColorSpace=sf.colorSpace;sw.imageExtent=r.extent;sw.imageArrayLayers=1;sw.imageUsage=VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;sw.imageSharingMode=VK_SHARING_MODE_EXCLUSIVE;sw.preTransform=caps.currentTransform;sw.compositeAlpha=VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;sw.presentMode=VK_PRESENT_MODE_FIFO_KHR;sw.clipped=VK_TRUE;if(!ok(vkCreateSwapchainKHR(r.device,&sw,nullptr,&r.swapchain),"vkCreateSwapchainKHR"))return false;vkGetSwapchainImagesKHR(r.device,r.swapchain,&count,nullptr);r.swapImages.resize(count);vkGetSwapchainImagesKHR(r.device,r.swapchain,&count,r.swapImages.data());
    for(auto image:r.swapImages){VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=image;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=r.swapFormat;vi.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};VkImageView v{};if(!ok(vkCreateImageView(r.device,&vi,nullptr,&v),"swap view"))return false;r.swapViews.push_back(v);}
    VkAttachmentDescription ad{};ad.format=r.swapFormat;ad.samples=VK_SAMPLE_COUNT_1_BIT;ad.loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;ad.storeOp=VK_ATTACHMENT_STORE_OP_STORE;ad.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;ad.finalLayout=VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;VkAttachmentReference ar{0,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};VkSubpassDescription sp{};sp.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sp.colorAttachmentCount=1;sp.pColorAttachments=&ar;VkRenderPassCreateInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};rp.attachmentCount=1;rp.pAttachments=&ad;rp.subpassCount=1;rp.pSubpasses=&sp;if(!ok(vkCreateRenderPass(r.device,&rp,nullptr,&r.renderPass),"render pass"))return false;
    for(auto v:r.swapViews){VkFramebufferCreateInfo fi{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};fi.renderPass=r.renderPass;fi.attachmentCount=1;fi.pAttachments=&v;fi.width=r.extent.width;fi.height=r.extent.height;fi.layers=1;VkFramebuffer f{};if(!ok(vkCreateFramebuffer(r.device,&fi,nullptr,&f),"framebuffer"))return false;r.framebuffers.push_back(f);}
    std::array<VkDescriptorSetLayoutBinding,3> bindings{};for(uint32_t i=0;i<3;i++){bindings[i].binding=i;bindings[i].descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;bindings[i].descriptorCount=1;bindings[i].stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT;}VkDescriptorSetLayoutCreateInfo sl{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};sl.bindingCount=3;sl.pBindings=bindings.data();if(!ok(vkCreateDescriptorSetLayout(r.device,&sl,nullptr,&r.setLayout),"set layout"))return false;VkPushConstantRange push{};push.stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT;push.offset=0;push.size=16;VkPipelineLayoutCreateInfo pl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pl.setLayoutCount=1;pl.pSetLayouts=&r.setLayout;pl.pushConstantRangeCount=1;pl.pPushConstantRanges=&push;if(!ok(vkCreatePipelineLayout(r.device,&pl,nullptr,&r.pipelineLayout),"pipeline layout"))return false;
    VkShaderModule vs=shader("camera.vert.spv"),fsmod=shader("camera.frag.spv");if(!vs||!fsmod)return false;VkPipelineShaderStageCreateInfo stages[2]={{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO},{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO}};stages[0].stage=VK_SHADER_STAGE_VERTEX_BIT;stages[0].module=vs;stages[0].pName="main";stages[1].stage=VK_SHADER_STAGE_FRAGMENT_BIT;stages[1].module=fsmod;stages[1].pName="main";VkPipelineVertexInputStateCreateInfo vertex{VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};VkPipelineInputAssemblyStateCreateInfo ia{VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};ia.topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;VkViewport vp{0,0,float(r.extent.width),float(r.extent.height),0,1};VkRect2D sc{{0,0},r.extent};VkPipelineViewportStateCreateInfo vsi{VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};vsi.viewportCount=1;vsi.pViewports=&vp;vsi.scissorCount=1;vsi.pScissors=&sc;VkPipelineRasterizationStateCreateInfo rs{VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};rs.polygonMode=VK_POLYGON_MODE_FILL;rs.cullMode=VK_CULL_MODE_NONE;rs.frontFace=VK_FRONT_FACE_COUNTER_CLOCKWISE;rs.lineWidth=1;VkPipelineMultisampleStateCreateInfo ms{VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};ms.rasterizationSamples=VK_SAMPLE_COUNT_1_BIT;VkPipelineColorBlendAttachmentState cba{};cba.colorWriteMask=0xf;VkPipelineColorBlendStateCreateInfo cb{VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};cb.attachmentCount=1;cb.pAttachments=&cba;VkGraphicsPipelineCreateInfo gp{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};gp.stageCount=2;gp.pStages=stages;gp.pVertexInputState=&vertex;gp.pInputAssemblyState=&ia;gp.pViewportState=&vsi;gp.pRasterizationState=&rs;gp.pMultisampleState=&ms;gp.pColorBlendState=&cb;gp.layout=r.pipelineLayout;gp.renderPass=r.renderPass;if(!ok(vkCreateGraphicsPipelines(r.device,VK_NULL_HANDLE,1,&gp,nullptr,&r.pipeline),"pipeline"))return false;vkDestroyShaderModule(r.device,vs,nullptr);vkDestroyShaderModule(r.device,fsmod,nullptr);
    VkCommandPoolCreateInfo cp{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};cp.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;cp.queueFamilyIndex=r.queueFamily;if(!ok(vkCreateCommandPool(r.device,&cp,nullptr,&r.commandPool),"command pool"))return false;VkCommandBufferAllocateInfo ca{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};ca.commandPool=r.commandPool;ca.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;ca.commandBufferCount=1;vkAllocateCommandBuffers(r.device,&ca,&r.command);VkQueryPoolCreateInfo qi{VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO};qi.queryType=VK_QUERY_TYPE_TIMESTAMP;qi.queryCount=8;if(!ok(vkCreateQueryPool(r.device,&qi,nullptr,&r.integratedQueryPool),"integrated query pool"))return false;VkSemaphoreCreateInfo sem{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};vkCreateSemaphore(r.device,&sem,nullptr,&r.acquired);vkCreateSemaphore(r.device,&sem,nullptr,&r.finished);VkFenceCreateInfo fen{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};fen.flags=VK_FENCE_CREATE_SIGNALED_BIT;vkCreateFence(r.device,&fen,nullptr,&r.fence);
    VkDescriptorPoolSize poolSize{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,3};VkDescriptorPoolCreateInfo dpi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};dpi.maxSets=1;dpi.poolSizeCount=1;dpi.pPoolSizes=&poolSize;vkCreateDescriptorPool(r.device,&dpi,nullptr,&r.descriptorPool);VkDescriptorSetAllocateInfo dai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};dai.descriptorPool=r.descriptorPool;dai.descriptorSetCount=1;dai.pSetLayouts=&r.setLayout;vkAllocateDescriptorSets(r.device,&dai,&r.descriptor);VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};si.magFilter=VK_FILTER_LINEAR;si.minFilter=VK_FILTER_LINEAR;si.addressModeU=si.addressModeV=si.addressModeW=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;si.maxLod=1;vkCreateSampler(r.device,&si,nullptr,&r.sampler);if(!createComputeStaticResources())return false;r.ready=true;return true;
}
void render(const uint8_t* y,const uint8_t* u,const uint8_t* v,int w,int h,int cw,int ch,uint16_t rotation,bool mirror) {
    if(!r.ready)return;if(r.textures[0].w!=w||r.textures[0].h!=h||r.textures[1].w!=cw||r.textures[1].h!=ch)if(!createFrameResources(w,h,cw,ch))return;vkWaitForFences(r.device,1,&r.fence,VK_TRUE,UINT64_MAX);
    void* mapped{};vkMapMemory(r.device,r.stagingMemory,0,r.stagingSize,0,&mapped);size_t ys=size_t(w)*h,cs=size_t(cw)*ch;memcpy(mapped,y,ys);memcpy(static_cast<uint8_t*>(mapped)+ys,u,cs);memcpy(static_cast<uint8_t*>(mapped)+ys+cs,v,cs);vkUnmapMemory(r.device,r.stagingMemory);
    uint32_t index=0;VkResult acq=vkAcquireNextImageKHR(r.device,r.swapchain,UINT64_MAX,r.acquired,VK_NULL_HANDLE,&index);if(acq!=VK_SUCCESS&&acq!=VK_SUBOPTIMAL_KHR)return;vkResetFences(r.device,1,&r.fence);vkResetCommandBuffer(r.command,0);VkCommandBufferBeginInfo begin{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};vkBeginCommandBuffer(r.command,&begin);
    size_t offsets[3]={0,ys,ys+cs};for(int i=0;i<3;i++){VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};b.srcAccessMask=0;b.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;b.oldLayout=VK_IMAGE_LAYOUT_UNDEFINED;b.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b.srcQueueFamilyIndex=b.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.image=r.textures[i].image;b.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&b);VkBufferImageCopy c{};c.bufferOffset=offsets[i];c.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};c.imageExtent={uint32_t(r.textures[i].w),uint32_t(r.textures[i].h),1};vkCmdCopyBufferToImage(r.command,r.staging,r.textures[i].image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&c);b.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;b.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;b.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,nullptr,0,nullptr,1,&b);}
    VkClearValue clear{{{0,0,0,1}}};VkRenderPassBeginInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};rp.renderPass=r.renderPass;rp.framebuffer=r.framebuffers[index];rp.renderArea={{0,0},r.extent};rp.clearValueCount=1;rp.pClearValues=&clear;vkCmdBeginRenderPass(r.command,&rp,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindPipeline(r.command,VK_PIPELINE_BIND_POINT_GRAPHICS,r.pipeline);vkCmdBindDescriptorSets(r.command,VK_PIPELINE_BIND_POINT_GRAPHICS,r.pipelineLayout,0,1,&r.descriptor,0,nullptr);struct Push{float scale[2];int32_t rotation;int32_t mirror;}push{{1.0f,1.0f},int32_t(rotation),mirror?1:0};const bool imageQuarterTurn=rotation==90||rotation==270;const float imageAspect=imageQuarterTurn?float(h)/float(w):float(w)/float(h);const bool surfaceQuarterTurn=r.surfaceTransform==VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR||r.surfaceTransform==VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR||r.surfaceTransform==VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR||r.surfaceTransform==VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR;const float screenAspect=surfaceQuarterTurn?float(r.extent.height)/float(r.extent.width):float(r.extent.width)/float(r.extent.height);if(imageAspect>screenAspect)push.scale[1]=screenAspect/imageAspect;else push.scale[0]=imageAspect/screenAspect;vkCmdPushConstants(r.command,r.pipelineLayout,VK_SHADER_STAGE_FRAGMENT_BIT,0,sizeof(push),&push);vkCmdDraw(r.command,3,1,0,0);vkCmdEndRenderPass(r.command);vkEndCommandBuffer(r.command);
    VkPipelineStageFlags waitStage=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO};submit.waitSemaphoreCount=1;submit.pWaitSemaphores=&r.acquired;submit.pWaitDstStageMask=&waitStage;submit.commandBufferCount=1;submit.pCommandBuffers=&r.command;submit.signalSemaphoreCount=1;submit.pSignalSemaphores=&r.finished;if(vkQueueSubmit(r.queue,1,&submit,r.fence)!=VK_SUCCESS)return;VkPresentInfoKHR present{VK_STRUCTURE_TYPE_PRESENT_INFO_KHR};present.waitSemaphoreCount=1;present.pWaitSemaphores=&r.finished;present.swapchainCount=1;present.pSwapchains=&r.swapchain;present.pImageIndices=&index;vkQueuePresentKHR(r.queue,&present);
}
void renderPreprocessedYuv(const uint8_t* y,const uint8_t* u,const uint8_t* v,int w,int h,int desiredW,int desiredH,int inputFormat,uint16_t rotation,bool mirror){
    if(!r.ready)return;if(!r.sobelPipeline||!r.medianPipeline)return;if(!createComputeFrameResources(w,h,desiredW,desiredH,inputFormat))return;int outW=r.computeOutW,outH=r.computeOutH;int chromaOutW=inputFormat==420?r.outUv.w:outW,chromaOutH=inputFormat==420?r.outUv.h:outH;if(r.textures[0].w!=outW||r.textures[0].h!=outH||r.textures[1].w!=chromaOutW||r.textures[1].h!=chromaOutH)if(!createFrameResources(outW,outH,chromaOutW,chromaOutH))return;
    static int64_t logStartNs=0;static uint32_t frames=0,gpuFrames=0;static double waitMs=0,uploadMs=0,acquireMs=0,recordMs=0,submitMs=0,presentMs=0,totalMs=0;static double gpuUploadCopyMs=0,gpuUploadBarrierMs=0,gpuDownsampleMs=0,gpuSobelMs=0,gpuSobelBarrierMs=0,gpuMedianMs=0,gpuFinalTextureCopyMs=0,gpuDrawMs=0;
    auto wallStart=std::chrono::high_resolution_clock::now();auto waitStart=std::chrono::high_resolution_clock::now();vkWaitForFences(r.device,1,&r.fence,VK_TRUE,UINT64_MAX);auto waitEnd=std::chrono::high_resolution_clock::now();r.frameBufferIndex=(r.frameBufferIndex+1u)%3u;updateComputeDescriptors();Buffer& yuvDownsampled=currentYuvDownsampled();Buffer& yuvFiltered=currentYuvFiltered();
    if(r.integratedQueryValid){uint64_t ts[8]{};if(vkGetQueryPoolResults(r.device,r.integratedQueryPool,0,8,sizeof(ts),ts,sizeof(uint64_t),VK_QUERY_RESULT_64_BIT|VK_QUERY_RESULT_WAIT_BIT)==VK_SUCCESS){const double p=r.properties.limits.timestampPeriod/1000000.0;double first=double(ts[1]-ts[0])*p;if(r.computePlan.passCount>0)gpuDownsampleMs+=first;else gpuUploadCopyMs+=first;gpuUploadBarrierMs+=double(ts[2]-ts[1])*p;gpuSobelMs+=double(ts[3]-ts[2])*p;gpuSobelBarrierMs+=double(ts[4]-ts[3])*p;gpuMedianMs+=double(ts[5]-ts[4])*p;gpuFinalTextureCopyMs+=double(ts[6]-ts[5])*p;gpuDrawMs+=double(ts[7]-ts[6])*p;gpuFrames++;}}
    auto uploadStart=std::chrono::high_resolution_clock::now();void* mapped{};vkMapMemory(r.device,r.compactUpload.memory,0,r.compactUpload.size,0,&mapped);size_t yPlaneBytes=size_t(w)*h;size_t uvPlaneBytes=inputFormat==420?size_t(w/2)*(h/2):yPlaneBytes;memcpy(mapped,y,yPlaneBytes);memcpy(static_cast<uint8_t*>(mapped)+yPlaneBytes,u,uvPlaneBytes);memcpy(static_cast<uint8_t*>(mapped)+yPlaneBytes+uvPlaneBytes,v,uvPlaneBytes);vkUnmapMemory(r.device,r.compactUpload.memory);auto uploadEnd=std::chrono::high_resolution_clock::now();
    auto acquireStart=std::chrono::high_resolution_clock::now();uint32_t index=0;VkResult acq=vkAcquireNextImageKHR(r.device,r.swapchain,UINT64_MAX,r.acquired,VK_NULL_HANDLE,&index);auto acquireEnd=std::chrono::high_resolution_clock::now();if(acq!=VK_SUCCESS&&acq!=VK_SUBOPTIMAL_KHR)return;auto recordStart=std::chrono::high_resolution_clock::now();vkResetFences(r.device,1,&r.fence);vkResetCommandBuffer(r.command,0);VkCommandBufferBeginInfo begin{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};vkBeginCommandBuffer(r.command,&begin);vkCmdResetQueryPool(r.command,r.integratedQueryPool,0,8);vkCmdWriteTimestamp(r.command,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,r.integratedQueryPool,0);
    auto copyPlaneRows=[&](uint32_t srcBase,uint32_t srcStride,uint32_t dstBase,uint32_t dstStride,uint32_t rowWords,uint32_t rows){for(uint32_t row=0;row<rows;row++){VkBufferCopy c{VkDeviceSize(srcBase+row*srcStride)*sizeof(uint32_t),VkDeviceSize(dstBase+row*dstStride)*sizeof(uint32_t),VkDeviceSize(rowWords)*sizeof(uint32_t)};vkCmdCopyBuffer(r.command,r.compactUpload.buffer,yuvDownsampled.buffer,1,&c);}};
    auto dispatchPass=[&](uint32_t passIndex,int mode,PlaneStorage srcY,PlaneStorage srcUv,PlaneStorage dstY,PlaneStorage dstUv,Buffer& dstBuffer){
        const bool resize=mode==6;vkCmdBindPipeline(r.command,VK_PIPELINE_BIND_POINT_COMPUTE,pipelineForMode(mode));
        for(uint32_t c=0;c<3;c++){const bool chroma=inputFormat==420&&c>0;const PlaneStorage src=chroma?srcUv:srcY;const PlaneStorage dst=chroma?dstUv:dstY;const uint32_t dstBase=c==0?0:(c==1?dstY.planeWords:dstY.planeWords+dstUv.planeWords);VkDescriptorSet set=resize?r.resizeSets[c]:r.downsampleSets[passIndex*3u+c];vkCmdBindDescriptorSets(r.command,VK_PIPELINE_BIND_POINT_COMPUTE,resize?r.resizeLayout:r.downsampleLayout,0,1,&set,0,nullptr);if(resize){ResizePush rp{src.strideWords,dst.strideWords,dstBase,uint32_t(src.w),uint32_t(src.h),uint32_t(dst.w),uint32_t(dst.h),uint32_t((dst.w+3)/4)};vkCmdPushConstants(r.command,r.resizeLayout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(rp),&rp);vkCmdDispatch(r.command,(rp.dst_word_count_x+127u)/128u,rp.dst_h,1);}else{DownsamplePush dp{src.strideWords,dst.strideWords,dstBase,mode==5?uint32_t(src.w)/16u:(mode==3?uint32_t(src.w)/12u:uint32_t(src.w)/8u),mode==5?uint32_t(src.h)/4u:(mode==3?uint32_t(src.h)/3u:uint32_t(src.h)/2u)};vkCmdPushConstants(r.command,r.downsampleLayout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(dp),&dp);vkCmdDispatch(r.command,(dp.tile_count_x+127u)/128u,dp.tile_count_y,1);}if(c+1u<3u){VkBufferMemoryBarrier db{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,VK_ACCESS_SHADER_WRITE_BIT,VK_ACCESS_SHADER_WRITE_BIT,VK_QUEUE_FAMILY_IGNORED,VK_QUEUE_FAMILY_IGNORED,dstBuffer.buffer,0,dstBuffer.size};vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,0,nullptr,1,&db,0,nullptr);}}};
    VkPipelineStageFlagBits downsampleTimestampStage=VK_PIPELINE_STAGE_TRANSFER_BIT;VkPipelineStageFlags downsampleDoneStage=VK_PIPELINE_STAGE_TRANSFER_BIT;VkAccessFlags downsampleWriteAccess=VK_ACCESS_TRANSFER_WRITE_BIT;
    if(r.computePlan.passCount==0){VkBufferMemoryBarrier hb{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,VK_ACCESS_HOST_WRITE_BIT,VK_ACCESS_TRANSFER_READ_BIT,VK_QUEUE_FAMILY_IGNORED,VK_QUEUE_FAMILY_IGNORED,r.compactUpload.buffer,0,r.compactUpload.size};vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_HOST_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,1,&hb,0,nullptr);copyPlaneRows(0,r.inputY.strideWords,0,r.outY.strideWords,uint32_t((r.outY.w+3)/4),uint32_t(r.outY.h));copyPlaneRows(r.inputY.planeWords,r.inputUv.strideWords,r.outY.planeWords,r.outUv.strideWords,uint32_t((r.outUv.w+3)/4),uint32_t(r.outUv.h));copyPlaneRows(r.inputY.planeWords+r.inputUv.planeWords,r.inputUv.strideWords,r.outY.planeWords+r.outUv.planeWords,r.outUv.strideWords,uint32_t((r.outUv.w+3)/4),uint32_t(r.outUv.h));}
    else{VkBufferMemoryBarrier hb{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,VK_ACCESS_HOST_WRITE_BIT,VK_ACCESS_SHADER_READ_BIT,VK_QUEUE_FAMILY_IGNORED,VK_QUEUE_FAMILY_IGNORED,r.compactUpload.buffer,0,r.compactUpload.size};vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_HOST_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,0,nullptr,1,&hb,0,nullptr);if(r.computePlan.passCount==1){dispatchPass(0,r.computePlan.modes[0],r.inputY,r.inputUv,r.outY,r.outUv,yuvDownsampled);}else{dispatchPass(0,r.computePlan.modes[0],r.inputY,r.inputUv,r.midY,r.midUv,r.yuvIntermediate);VkBufferMemoryBarrier ib{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,VK_ACCESS_SHADER_WRITE_BIT,VK_ACCESS_SHADER_READ_BIT,VK_QUEUE_FAMILY_IGNORED,VK_QUEUE_FAMILY_IGNORED,r.yuvIntermediate.buffer,0,r.yuvIntermediate.size};vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,0,nullptr,1,&ib,0,nullptr);dispatchPass(1,r.computePlan.modes[1],r.midY,r.midUv,r.outY,r.outUv,yuvDownsampled);}downsampleTimestampStage=VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT;downsampleDoneStage=VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT;downsampleWriteAccess=VK_ACCESS_SHADER_WRITE_BIT;}
    vkCmdWriteTimestamp(r.command,downsampleTimestampStage,r.integratedQueryPool,1);
    VkBufferMemoryBarrier b0{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,downsampleWriteAccess,VK_ACCESS_SHADER_READ_BIT,VK_QUEUE_FAMILY_IGNORED,VK_QUEUE_FAMILY_IGNORED,yuvDownsampled.buffer,0,yuvDownsampled.size};vkCmdPipelineBarrier(r.command,downsampleDoneStage,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,0,nullptr,1,&b0,0,nullptr);
    vkCmdWriteTimestamp(r.command,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,r.integratedQueryPool,2);
    vkCmdBindPipeline(r.command,VK_PIPELINE_BIND_POINT_COMPUTE,r.sobelPipeline);if(inputFormat==420){for(uint32_t c=0;c<3;c++){const bool chroma=c>0;const uint32_t pw=chroma?uint32_t(chromaOutW):uint32_t(outW),ph=chroma?uint32_t(chromaOutH):uint32_t(outH),sw=chroma?r.computeChromaStrideWords:r.computeStrideWords,pl=chroma?r.computeChromaPlaneWords:r.computePlaneWords;vkCmdBindDescriptorSets(r.command,VK_PIPELINE_BIND_POINT_COMPUTE,r.sobelLayout,0,1,&r.sobelPlaneSets[c],0,nullptr);SobelPush sp{pw,ph,sw,pl};vkCmdPushConstants(r.command,r.sobelLayout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(sp),&sp);vkCmdDispatch(r.command,(sw+31u)/32u,ph,1);}}else{vkCmdBindDescriptorSets(r.command,VK_PIPELINE_BIND_POINT_COMPUTE,r.sobelLayout,0,1,&r.sobelSet,0,nullptr);SobelPush sp{uint32_t(outW),uint32_t(outH),r.computeStrideWords,r.computePlaneWords};vkCmdPushConstants(r.command,r.sobelLayout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(sp),&sp);vkCmdDispatch(r.command,(r.computeStrideWords+31u)/32u,uint32_t(outH),3);}
    vkCmdWriteTimestamp(r.command,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,r.integratedQueryPool,3);
    VkBufferMemoryBarrier b1{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,VK_ACCESS_SHADER_WRITE_BIT,VK_ACCESS_SHADER_READ_BIT,VK_QUEUE_FAMILY_IGNORED,VK_QUEUE_FAMILY_IGNORED,r.sobelMask.buffer,0,r.sobelMask.size};vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,0,nullptr,1,&b1,0,nullptr);
    vkCmdWriteTimestamp(r.command,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,r.integratedQueryPool,4);
    vkCmdBindPipeline(r.command,VK_PIPELINE_BIND_POINT_COMPUTE,r.medianPipeline);if(inputFormat==420){for(uint32_t c=0;c<3;c++){const bool chroma=c>0;const uint32_t pw=chroma?uint32_t(chromaOutW):uint32_t(outW),ph=chroma?uint32_t(chromaOutH):uint32_t(outH),sw=chroma?r.computeChromaStrideWords:r.computeStrideWords,pl=chroma?r.computeChromaPlaneWords:r.computePlaneWords;vkCmdBindDescriptorSets(r.command,VK_PIPELINE_BIND_POINT_COMPUTE,r.medianLayout,0,1,&r.medianPlaneSets[c],0,nullptr);MedianPush mp{pw,ph,sw,pl,80u,40u};vkCmdPushConstants(r.command,r.medianLayout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(mp),&mp);vkCmdDispatch(r.command,(sw+31u)/32u,ph,1);}}else{vkCmdBindDescriptorSets(r.command,VK_PIPELINE_BIND_POINT_COMPUTE,r.medianLayout,0,1,&r.medianSet,0,nullptr);MedianPush mp{uint32_t(outW),uint32_t(outH),r.computeStrideWords,r.computePlaneWords,80u,40u};vkCmdPushConstants(r.command,r.medianLayout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(mp),&mp);vkCmdDispatch(r.command,(r.computeStrideWords+31u)/32u,uint32_t(outH),3);}
    vkCmdWriteTimestamp(r.command,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,r.integratedQueryPool,5);
    VkBufferMemoryBarrier b2{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,VK_ACCESS_SHADER_WRITE_BIT,VK_ACCESS_TRANSFER_READ_BIT,VK_QUEUE_FAMILY_IGNORED,VK_QUEUE_FAMILY_IGNORED,yuvFiltered.buffer,0,yuvFiltered.size};vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,1,&b2,0,nullptr);
    size_t yOutBytes=VkDeviceSize(r.computePlaneWords)*sizeof(uint32_t),uvPaddedBytes=VkDeviceSize(r.computeChromaPlaneWords)*sizeof(uint32_t);size_t offsets[3]={0,yOutBytes,yOutBytes+uvPaddedBytes};for(int i=0;i<3;i++){VkImageMemoryBarrier ib{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};ib.srcAccessMask=0;ib.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;ib.oldLayout=VK_IMAGE_LAYOUT_UNDEFINED;ib.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;ib.srcQueueFamilyIndex=ib.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;ib.image=r.textures[i].image;ib.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&ib);VkBufferImageCopy c{};c.bufferOffset=offsets[i];c.bufferRowLength=i>0?uint32_t(r.computeChromaOutW):uint32_t(r.computePaddedOutW);c.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};c.imageExtent={uint32_t(r.textures[i].w),uint32_t(r.textures[i].h),1};vkCmdCopyBufferToImage(r.command,yuvFiltered.buffer,r.textures[i].image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&c);ib.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;ib.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;ib.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;ib.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;vkCmdPipelineBarrier(r.command,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,nullptr,0,nullptr,1,&ib);}
    vkCmdWriteTimestamp(r.command,VK_PIPELINE_STAGE_TRANSFER_BIT,r.integratedQueryPool,6);
    VkClearValue clear{{{0,0,0,1}}};VkRenderPassBeginInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};rp.renderPass=r.renderPass;rp.framebuffer=r.framebuffers[index];rp.renderArea={{0,0},r.extent};rp.clearValueCount=1;rp.pClearValues=&clear;vkCmdBeginRenderPass(r.command,&rp,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindPipeline(r.command,VK_PIPELINE_BIND_POINT_GRAPHICS,r.pipeline);vkCmdBindDescriptorSets(r.command,VK_PIPELINE_BIND_POINT_GRAPHICS,r.pipelineLayout,0,1,&r.descriptor,0,nullptr);struct Push{float scale[2];int32_t rotation;int32_t mirror;}push{{1.0f,1.0f},int32_t(rotation),mirror?1:0};const bool imageQuarterTurn=rotation==90||rotation==270;const float imageAspect=imageQuarterTurn?float(outH)/float(outW):float(outW)/float(outH);const bool surfaceQuarterTurn=r.surfaceTransform==VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR||r.surfaceTransform==VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR||r.surfaceTransform==VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR||r.surfaceTransform==VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR;const float screenAspect=surfaceQuarterTurn?float(r.extent.height)/float(r.extent.width):float(r.extent.width)/float(r.extent.height);if(imageAspect>screenAspect)push.scale[1]=screenAspect/imageAspect;else push.scale[0]=imageAspect/screenAspect;vkCmdPushConstants(r.command,r.pipelineLayout,VK_SHADER_STAGE_FRAGMENT_BIT,0,sizeof(push),&push);vkCmdDraw(r.command,3,1,0,0);vkCmdEndRenderPass(r.command);vkCmdWriteTimestamp(r.command,VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,r.integratedQueryPool,7);vkEndCommandBuffer(r.command);auto recordEnd=std::chrono::high_resolution_clock::now();
    auto submitStart=std::chrono::high_resolution_clock::now();VkPipelineStageFlags waitStage=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO};submit.waitSemaphoreCount=1;submit.pWaitSemaphores=&r.acquired;submit.pWaitDstStageMask=&waitStage;submit.commandBufferCount=1;submit.pCommandBuffers=&r.command;submit.signalSemaphoreCount=1;submit.pSignalSemaphores=&r.finished;if(vkQueueSubmit(r.queue,1,&submit,r.fence)!=VK_SUCCESS)return;r.integratedQueryValid=true;r.latestFilteredReady=true;if(r.filteredFrameCount<3u)r.filteredFrameCount++;auto submitEnd=std::chrono::high_resolution_clock::now();auto presentStart=std::chrono::high_resolution_clock::now();VkPresentInfoKHR present{VK_STRUCTURE_TYPE_PRESENT_INFO_KHR};present.waitSemaphoreCount=1;present.pWaitSemaphores=&r.finished;present.swapchainCount=1;present.pSwapchains=&r.swapchain;present.pImageIndices=&index;vkQueuePresentKHR(r.queue,&present);auto wallEnd=std::chrono::high_resolution_clock::now();
    auto nowNs=std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now().time_since_epoch()).count();if(!logStartNs)logStartNs=nowNs;frames++;waitMs+=std::chrono::duration<double,std::milli>(waitEnd-waitStart).count();uploadMs+=std::chrono::duration<double,std::milli>(uploadEnd-uploadStart).count();acquireMs+=std::chrono::duration<double,std::milli>(acquireEnd-acquireStart).count();recordMs+=std::chrono::duration<double,std::milli>(recordEnd-recordStart).count();submitMs+=std::chrono::duration<double,std::milli>(submitEnd-submitStart).count();presentMs+=std::chrono::duration<double,std::milli>(wallEnd-presentStart).count();totalMs+=std::chrono::duration<double,std::milli>(wallEnd-wallStart).count();if(nowNs-logStartNs>=1000000000LL){double f=frames;double gf=gpuFrames?double(gpuFrames):1.0;LOGI_NATIVE("integrated gpu preview avg over %u frames | input=yuv%d | output_y=%dx%d padded_y=%dx%d output_uv=%dx%d padded_uv=%dx%d | wait_previous_gpu=%.2f ms | cpu_upload_yuv%d=%.2f ms | acquire_swapchain=%.2f ms | cpu_record_compute_render=%.2f ms | queue_submit=%.2f ms | queue_present=%.2f ms | gpu_downsample=%.2f ms%s | gpu_downsample_to_sobel_barrier=%.2f ms | gpu_sobel=%.2f ms | gpu_sobel_to_median_barrier=%.2f ms | gpu_median=%.2f ms | gpu_final_yuv_to_textures=%.2f ms | gpu_draw=%.2f ms | total_renderer_integrated=%.2f ms | no_cpu_output_readback | %dx%d -> %dx%d",frames,inputFormat,outW,outH,r.computePaddedOutW,r.computePaddedOutH,chromaOutW,chromaOutH,r.computeChromaOutW,r.computeChromaOutH,waitMs/f,inputFormat,uploadMs/f,acquireMs/f,recordMs/f,submitMs/f,presentMs/f,(gpuUploadCopyMs+gpuDownsampleMs)/gf,r.computePlan.passCount==0?" (1x1 pass-through)":"",gpuUploadBarrierMs/gf,gpuSobelMs/gf,gpuSobelBarrierMs/gf,gpuMedianMs/gf,gpuFinalTextureCopyMs/gf,gpuDrawMs/gf,totalMs/f,w,h,outW,outH);logStartNs=nowNs;frames=0;gpuFrames=0;waitMs=uploadMs=acquireMs=recordMs=submitMs=presentMs=totalMs=0;gpuUploadCopyMs=gpuUploadBarrierMs=gpuDownsampleMs=gpuSobelMs=gpuSobelBarrierMs=gpuMedianMs=gpuFinalTextureCopyMs=gpuDrawMs=0;}
}
}
uint8_t clampByte(int value){return uint8_t(value<0?0:(value>255?255:value));}
bool copyLatestFilteredArgbLocked(std::vector<uint32_t>& argb,int& width,int& height){
    if(!r.ready||!r.latestFilteredReady||!currentYuvFiltered().buffer||r.computeInputFormat!=420)return false;
    if(vkWaitForFences(r.device,1,&r.fence,VK_TRUE,UINT64_MAX)!=VK_SUCCESS)return false;
    Buffer& src=currentYuvFiltered();Buffer readback{};
    if(!createBuffer(readback,src.size,VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,"camera filtered readback"))return false;
    vkResetFences(r.device,1,&r.fence);vkResetCommandBuffer(r.command,0);VkCommandBufferBeginInfo begin{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};if(vkBeginCommandBuffer(r.command,&begin)!=VK_SUCCESS){destroyBuffer(readback);return false;}
    VkBufferCopy copy{0,0,src.size};vkCmdCopyBuffer(r.command,src.buffer,readback.buffer,1,&copy);vkEndCommandBuffer(r.command);
    VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO};submit.commandBufferCount=1;submit.pCommandBuffers=&r.command;if(vkQueueSubmit(r.queue,1,&submit,r.fence)!=VK_SUCCESS){destroyBuffer(readback);return false;}
    if(vkWaitForFences(r.device,1,&r.fence,VK_TRUE,UINT64_MAX)!=VK_SUCCESS){destroyBuffer(readback);return false;}
    void* mapped{};if(vkMapMemory(r.device,readback.memory,0,readback.size,0,&mapped)!=VK_SUCCESS){destroyBuffer(readback);return false;}
    const auto* bytes=static_cast<const uint8_t*>(mapped);width=r.computeOutW;height=r.computeOutH;argb.assign(size_t(width)*height,0xff000000u);
    const size_t yOffset=0;const size_t uOffset=VkDeviceSize(r.computePlaneWords)*sizeof(uint32_t);const size_t vOffset=uOffset+VkDeviceSize(r.computeChromaPlaneWords)*sizeof(uint32_t);
    const int yStride=int(r.computeStrideWords)*4;const int uvStride=int(r.computeChromaStrideWords)*4;
    for(int py=0;py<height;py++){const uint8_t* yRow=bytes+yOffset+size_t(py)*yStride;const uint8_t* uRow=bytes+uOffset+size_t(py/2)*uvStride;const uint8_t* vRow=bytes+vOffset+size_t(py/2)*uvStride;for(int px=0;px<width;px++){const int yy=yRow[px];const int uu=int(uRow[px/2])-128;const int vv=int(vRow[px/2])-128;const uint8_t rr=clampByte(int(yy+1.402f*vv));const uint8_t gg=clampByte(int(yy-0.344136f*uu-0.714136f*vv));const uint8_t bb=clampByte(int(yy+1.772f*uu));argb[size_t(py)*width+px]=0xff000000u|(uint32_t(rr)<<16u)|(uint32_t(gg)<<8u)|uint32_t(bb);}}
    vkUnmapMemory(r.device,readback.memory);destroyBuffer(readback);return true;
}
bool copyYuv420RingsLocked(std::array<std::vector<uint8_t>,3>& downsampledFrames,std::array<std::vector<uint8_t>,3>& filteredFrames,int& width,int& height,int& chromaWidth,int& chromaHeight,int& paddedWidth,int& paddedHeight,int& paddedChromaWidth,int& paddedChromaHeight){
    if(!r.ready||!r.latestFilteredReady||r.filteredFrameCount<3u||!r.yuvDownsampled[0].buffer||!r.yuvFiltered[0].buffer||r.computeInputFormat!=420)return false;
    if(vkWaitForFences(r.device,1,&r.fence,VK_TRUE,UINT64_MAX)!=VK_SUCCESS)return false;
    const VkDeviceSize frameSize=r.yuvFiltered[0].size;Buffer readback{};
    if(!createBuffer(readback,frameSize*6u,VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,"camera yuv ring readback"))return false;
    vkResetFences(r.device,1,&r.fence);vkResetCommandBuffer(r.command,0);VkCommandBufferBeginInfo begin{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};if(vkBeginCommandBuffer(r.command,&begin)!=VK_SUCCESS){destroyBuffer(readback);return false;}
    const uint32_t order[3]={r.frameBufferIndex,(r.frameBufferIndex+2u)%3u,(r.frameBufferIndex+1u)%3u};
    for(uint32_t i=0;i<3u;i++){VkBufferCopy copy{0,frameSize*i,frameSize};vkCmdCopyBuffer(r.command,r.yuvDownsampled[order[i]].buffer,readback.buffer,1,&copy);}
    for(uint32_t i=0;i<3u;i++){VkBufferCopy copy{0,frameSize*(i+3u),frameSize};vkCmdCopyBuffer(r.command,r.yuvFiltered[order[i]].buffer,readback.buffer,1,&copy);}
    vkEndCommandBuffer(r.command);VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO};submit.commandBufferCount=1;submit.pCommandBuffers=&r.command;if(vkQueueSubmit(r.queue,1,&submit,r.fence)!=VK_SUCCESS){destroyBuffer(readback);return false;}
    if(vkWaitForFences(r.device,1,&r.fence,VK_TRUE,UINT64_MAX)!=VK_SUCCESS){destroyBuffer(readback);return false;}
    void* mapped{};if(vkMapMemory(r.device,readback.memory,0,readback.size,0,&mapped)!=VK_SUCCESS){destroyBuffer(readback);return false;}
    const auto* bytes=static_cast<const uint8_t*>(mapped);for(uint32_t i=0;i<3u;i++){downsampledFrames[i].assign(bytes+size_t(frameSize)*i,bytes+size_t(frameSize)*(i+1u));filteredFrames[i].assign(bytes+size_t(frameSize)*(i+3u),bytes+size_t(frameSize)*(i+4u));}
    vkUnmapMemory(r.device,readback.memory);destroyBuffer(readback);
    width=r.computeOutW;height=r.computeOutH;chromaWidth=r.outUv.w;chromaHeight=r.outUv.h;paddedWidth=r.computePaddedOutW;paddedHeight=r.computePaddedOutH;paddedChromaWidth=r.computeChromaOutW;paddedChromaHeight=r.computeChromaOutH;return true;
}
std::string vulkanSetWindow(ANativeWindow* window,AAssetManager* assets){std::lock_guard<std::mutex> lock(mutex);destroyAll();if(!window||!assets)return "Vulkan surface released";if(!init(window,assets)){destroyAll();return "Error: Vulkan initialization failed (see CameraVulkan log)";}std::ostringstream s;s<<"Vulkan SurfaceView ready | swapchain "<<r.extent.width<<"x"<<r.extent.height;return s.str();}
void vulkanDestroy(){std::lock_guard<std::mutex> lock(mutex);destroyAll();}
void vulkanSubmitYuv420(const uint8_t* y,const uint8_t* u,const uint8_t* v,int w,int h,uint16_t rotation,bool mirror){std::lock_guard<std::mutex> lock(mutex);render(y,u,v,w,h,w/2,h/2,rotation,mirror);}
void vulkanSubmitYuv444(const uint8_t* y,const uint8_t* u,const uint8_t* v,int w,int h,uint16_t rotation,bool mirror){std::lock_guard<std::mutex> lock(mutex);render(y,u,v,w,h,w,h,rotation,mirror);}
void vulkanSubmitPreprocessedYuv444(const uint8_t* y,const uint8_t* u,const uint8_t* v,int w,int h,int desiredW,int desiredH,uint16_t rotation,bool mirror){std::lock_guard<std::mutex> lock(mutex);renderPreprocessedYuv(y,u,v,w,h,desiredW,desiredH,444,rotation,mirror);}
void vulkanSubmitPreprocessedYuv420(const uint8_t* y,const uint8_t* u,const uint8_t* v,int w,int h,int desiredW,int desiredH,uint16_t rotation,bool mirror){std::lock_guard<std::mutex> lock(mutex);renderPreprocessedYuv(y,u,v,w,h,desiredW,desiredH,420,rotation,mirror);}
bool vulkanCopyLatestFilteredArgb(std::vector<uint32_t>& argb,int& width,int& height){std::lock_guard<std::mutex> lock(mutex);return copyLatestFilteredArgbLocked(argb,width,height);}
bool vulkanCopyYuv420Rings(std::array<std::vector<uint8_t>,3>& downsampledFrames,std::array<std::vector<uint8_t>,3>& filteredFrames,int& width,int& height,int& chromaWidth,int& chromaHeight,int& paddedWidth,int& paddedHeight,int& paddedChromaWidth,int& paddedChromaHeight){std::lock_guard<std::mutex> lock(mutex);return copyYuv420RingsLocked(downsampledFrames,filteredFrames,width,height,chromaWidth,chromaHeight,paddedWidth,paddedHeight,paddedChromaWidth,paddedChromaHeight);}
